GET http://localhost:5000/api/project

###
PUT http://localhost:5000/api/project/update
Content-Type: "application/json",
{
  "title": "update",
  "date": 123445655,
  "descripsi": "update des",
  "projectId": "-N-mVZcAvVSasPwIKMzV"
}